<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HeroSliderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sliders = [
            [
                'title_id' => 'Wujudkan Impian Bekerja di Jepang',
                'title_en' => 'Realize Your Dream of Working in Japan',
                'title_jp' => '日本で働く夢を実現',
                'subtitle_id' => 'Program Profesional dengan Gaji Kompetitif',
                'subtitle_en' => 'Professional Program with Competitive Salary',
                'subtitle_jp' => '競争力のある給与の専門プログラム',
                'country_id' => 'Jepang',
                'country_en' => 'Japan',
                'country_jp' => '日本',
                'description_id' => 'Bergabunglah dengan ribuan alumni yang telah sukses bekerja di Jepang melalui program kami. Dapatkan gaji kompetitif, benefit lengkap, dan kesempatan pengembangan karir.',
                'description_en' => 'Join thousands of alumni who have successfully worked in Japan through our program. Get competitive salary, complete benefits, and career development opportunities.',
                'description_jp' => '私たちのプログラムを通じて日本で成功した何千人もの卒業生に参加してください。競争力のある給与、完全な福利厚生、キャリア開発の機会を獲得してください。',
                'background_image' => 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Daftar Sekarang',
                'button_text_en' => 'Register Now',
                'button_text_jp' => '今すぐ登録',
                'button_link' => '/program',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 1,
                'status' => 'Publish',
            ],
            [
                'title_id' => 'Belajar Bahasa Jepang dengan Metode Terbaik',
                'title_en' => 'Learn Japanese with the Best Method',
                'title_jp' => '最高の方法で日本語を学ぶ',
                'subtitle_id' => 'Kurikulum Internasional & Instruktur Profesional',
                'subtitle_en' => 'International Curriculum & Professional Instructors',
                'subtitle_jp' => '国際カリキュラムと専門講師',
                'country_id' => 'Indonesia',
                'country_en' => 'Indonesia',
                'country_jp' => 'インドネシア',
                'description_id' => 'Program pembelajaran bahasa Jepang dengan kurikulum terstruktur. Siapkan diri Anda untuk lulus JLPT dan bekerja di Jepang dengan percaya diri.',
                'description_en' => 'Japanese language learning program with structured curriculum. Prepare yourself to pass JLPT and work in Japan with confidence.',
                'description_jp' => '構造化されたカリキュラムによる日本語学習プログラム。JLPTに合格し、自信を持って日本で働く準備をしてください。',
                'background_image' => 'https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Lihat Program',
                'button_text_en' => 'View Program',
                'button_text_jp' => 'プログラムを見る',
                'button_link' => '/program',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 2,
                'status' => 'Publish',
            ],
            [
                'title_id' => '1000+ Alumni Sukses Bekerja di Jepang',
                'title_en' => '1000+ Alumni Successfully Working in Japan',
                'title_jp' => '1000人以上の卒業生が日本で成功',
                'subtitle_id' => 'Bergabunglah dengan Komunitas Sukses Kami',
                'subtitle_en' => 'Join Our Success Community',
                'subtitle_jp' => '私たちの成功コミュニティに参加',
                'country_id' => 'Jepang',
                'country_en' => 'Japan',
                'country_jp' => '日本',
                'description_id' => 'Lebih dari 1000 alumni telah berhasil bekerja di berbagai sektor di Jepang. Jadilah bagian dari komunitas sukses kami dan wujudkan impian Anda.',
                'description_en' => 'More than 1000 alumni have successfully worked in various sectors in Japan. Be part of our success community and realize your dreams.',
                'description_jp' => '1000人以上の卒業生が日本で様々な分野で成功しています。私たちの成功コミュニティの一員になり、あなたの夢を実現してください。',
                'background_image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Lihat Testimoni',
                'button_text_en' => 'View Testimonials',
                'button_text_jp' => 'お客様の声を見る',
                'button_link' => '/kisah-sukses',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
                    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 3,
                'status' => 'Publish',
            ],
            [
                'title_id' => 'Program Visa Terjamin & Legal',
                'title_en' => 'Guaranteed & Legal Visa Program',
                'title_jp' => '保証された合法的なビザプログラム',
                'subtitle_id' => 'Dukungan Penuh Hingga Berangkat',
                'subtitle_en' => 'Full Support Until Departure',
                'subtitle_jp' => '出発まで完全サポート',
                'country_id' => 'Jepang',
                'country_en' => 'Japan',
                'country_jp' => '日本',
                'description_id' => 'Kami membantu Anda mengurus visa kerja dengan proses yang legal dan terjamin. Tim konsultan kami siap membantu dari awal hingga Anda berangkat ke Jepang.',
                'description_en' => 'We help you process work visas through legal and guaranteed procedures. Our consultant team is ready to assist from the beginning until you depart for Japan.',
                'description_jp' => '私たちは合法的で保証された手順で就労ビザの処理をお手伝いします。コンサルタントチームが最初から日本への出発までサポートします。',
                'background_image' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Konsultasi Gratis',
                'button_text_en' => 'Free Consultation',
                'button_text_jp' => '無料相談',
                'button_link' => '/kontak',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 4,
                'status' => 'Publish',
            ],
            [
                'title_id' => 'Gaji Kompetitif & Benefit Lengkap',
                'title_en' => 'Competitive Salary & Complete Benefits',
                'title_jp' => '競争力のある給与と完全な福利厚生',
                'subtitle_id' => 'Mulai dari ¥2.2 Juta/Bulan',
                'subtitle_en' => 'Starting from ¥2.2 Million/Month',
                'subtitle_jp' => '月額220万円から',
                'country_id' => 'Jepang',
                'country_en' => 'Japan',
                'country_jp' => '日本',
                'description_id' => 'Dapatkan gaji kompetitif mulai dari ¥2.2 juta per bulan dengan benefit lengkap termasuk asuransi kesehatan, tunjangan keluarga, dan bonus tahunan.',
                'description_en' => 'Get competitive salary starting from ¥2.2 million per month with complete benefits including health insurance, family allowance, and annual bonus.',
                'description_jp' => '月額220万円から始まる競争力のある給与と、健康保険、家族手当、年間ボーナスを含む完全な福利厚生を獲得してください。',
                'background_image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Lihat Lowongan',
                'button_text_en' => 'View Jobs',
                'button_text_jp' => '求人を見る',
                'button_link' => '/loker',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 5,
                'status' => 'Publish',
            ],
            [
                'title_id' => 'Pelatihan Profesional & Sertifikasi',
                'title_en' => 'Professional Training & Certification',
                'title_jp' => '専門トレーニングと認定',
                'subtitle_id' => 'Siap Kerja dengan Skill Terbaik',
                'subtitle_en' => 'Ready to Work with Best Skills',
                'subtitle_jp' => '最高のスキルで就業準備完了',
                'country_id' => 'Indonesia',
                'country_en' => 'Indonesia',
                'country_jp' => 'インドネシア',
                'description_id' => 'Dapatkan pelatihan profesional dan sertifikasi sebelum berangkat ke Jepang. Kami memastikan Anda siap bekerja dengan skill terbaik di industri pilihan Anda.',
                'description_en' => 'Get professional training and certification before departing to Japan. We ensure you are ready to work with the best skills in your chosen industry.',
                'description_jp' => '日本への出発前に専門トレーニングと認定を取得してください。選択した業界で最高のスキルで働く準備ができていることを保証します。',
                'background_image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Pelajari Program',
                'button_text_en' => 'Learn Program',
                'button_text_jp' => 'プログラムを学ぶ',
                'button_link' => '/program',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 6,
                'status' => 'Publish',
            ],
            [
                'title_id' => 'Kerjasama dengan Perusahaan Terkemuka',
                'title_en' => 'Partnership with Leading Companies',
                'title_jp' => '大手企業とのパートナーシップ',
                'subtitle_id' => 'Toyota, Honda, Panasonic & Lainnya',
                'subtitle_en' => 'Toyota, Honda, Panasonic & More',
                'subtitle_jp' => 'トヨタ、ホンダ、パナソニックなど',
                'country_id' => 'Jepang',
                'country_en' => 'Japan',
                'country_jp' => '日本',
                'description_id' => 'Kami memiliki kerjasama dengan puluhan perusahaan terkemuka di Jepang seperti Toyota, Honda, Panasonic, dan banyak lagi. Dapatkan kesempatan bekerja di perusahaan kelas dunia.',
                'description_en' => 'We have partnerships with dozens of leading companies in Japan such as Toyota, Honda, Panasonic, and many more. Get the opportunity to work at world-class companies.',
                'description_jp' => 'トヨタ、ホンダ、パナソニックなど、日本で数十の大手企業とパートナーシップを結んでいます。世界クラスの企業で働く機会を得てください。',
                'background_image' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Lihat Perusahaan',
                'button_text_en' => 'View Companies',
                'button_text_jp' => '企業を見る',
                'button_link' => '/industri',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 7,
                'status' => 'Publish',
            ],
            [
                'title_id' => 'Support 24/7 Selama di Jepang',
                'title_en' => '24/7 Support While in Japan',
                'title_jp' => '日本での24時間サポート',
                'subtitle_id' => 'Tim Lokal Siap Membantu',
                'subtitle_en' => 'Local Team Ready to Help',
                'subtitle_jp' => '支援準備が整った現地チーム',
                'country_id' => 'Jepang',
                'country_en' => 'Japan',
                'country_jp' => '日本',
                'description_id' => 'Tim support kami di Jepang siap membantu Anda 24/7. Dari masalah visa, akomodasi, hingga adaptasi budaya, kami selalu siap membantu.',
                'description_en' => 'Our support team in Japan is ready to help you 24/7. From visa issues, accommodation, to cultural adaptation, we are always ready to help.',
                'description_jp' => '日本のサポートチームが24時間体制でサポートします。ビザの問題、宿泊施設、文化的適応まで、常にサポートの準備ができています。',
                'background_image' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1920&q=80',
                'person_image' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
                'button_text_id' => 'Hubungi Kami',
                'button_text_en' => 'Contact Us',
                'button_text_jp' => 'お問い合わせ',
                'button_link' => '/kontak',
                'video_link' => null,
                'person_images' => json_encode([
                    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
                ]),
                'urutan' => 8,
                'status' => 'Publish',
            ],
        ];

        DB::table('hero_sliders')->insert($sliders);
    }
}
