<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KisahSuksesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kisahSukses = [
            [
                'nama' => 'Budi Santoso',
                'pekerjaan' => 'Production Worker',
                'lokasi' => 'Toyota Plant, Aichi',
                'testimoni' => 'Saya sangat bersyukur bisa bekerja di Toyota melalui program Meganthara Group. Gaji yang saya terima sangat membantu keluarga di Indonesia. Lingkungan kerja sangat baik dan rekan kerja Jepang sangat ramah. Saya sudah bekerja 3 tahun dan sangat puas dengan program ini.',
                'foto' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Manufaktur',
                'tahun' => 2022,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 1,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Siti Nurhaliza',
                'pekerjaan' => 'Caregiver',
                'lokasi' => 'Osaka Care Facility',
                'testimoni' => 'Menjadi caregiver di Jepang adalah impian saya. Melalui program Meganthara Group, saya bisa mewujudkan impian tersebut. Saya belajar banyak tentang budaya Jepang dan cara merawat lansia dengan baik. Gaji yang saya terima cukup untuk membantu keluarga dan menabung untuk masa depan.',
                'foto' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Care Worker',
                'tahun' => 2021,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 2,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Ahmad Rizki',
                'pekerjaan' => 'Hotel Staff',
                'lokasi' => 'Grand Hotel, Tokyo',
                'testimoni' => 'Bekerja di hotel di Tokyo adalah pengalaman yang luar biasa. Saya belajar banyak tentang service excellence ala Jepang. Meganthara Group membantu saya dari awal hingga mendapatkan visa dan bekerja. Tim support mereka sangat responsif dan membantu.',
                'foto' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Hospitality',
                'tahun' => 2023,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 3,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Dewi Lestari',
                'pekerjaan' => 'Quality Control',
                'lokasi' => 'Panasonic Factory, Osaka',
                'testimoni' => 'Saya bekerja sebagai quality control di pabrik Panasonic. Program ini memberikan saya kesempatan untuk belajar teknologi canggih dan standar kualitas Jepang. Gaji saya sekarang sudah 3.2 juta per bulan dan saya sangat puas dengan benefit yang diberikan perusahaan.',
                'foto' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Manufaktur',
                'tahun' => 2022,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 4,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Rudi Hermawan',
                'pekerjaan' => 'Construction Worker',
                'lokasi' => 'Tokyo Construction Site',
                'testimoni' => 'Bekerja di konstruksi di Tokyo memberikan saya pengalaman berharga. Saya belajar tentang teknologi konstruksi modern Jepang dan standar keselamatan yang sangat ketat. Gaji yang saya terima sangat baik dan saya bisa mengirim uang untuk keluarga setiap bulan.',
                'foto' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Konstruksi',
                'tahun' => 2023,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 5,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Maya Sari',
                'pekerjaan' => 'Restaurant Staff',
                'lokasi' => 'Sushi Restaurant, Kyoto',
                'testimoni' => 'Bekerja di restoran sushi di Kyoto adalah pengalaman yang sangat menyenangkan. Saya belajar cara membuat sushi autentik dan melayani pelanggan dengan baik. Budaya kerja Jepang mengajarkan saya tentang disiplin dan dedikasi. Program Meganthara Group sangat membantu perjalanan saya.',
                'foto' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Food Service',
                'tahun' => 2022,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 6,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Andi Pratama',
                'pekerjaan' => 'Machine Operator',
                'lokasi' => 'Honda Factory, Saitama',
                'testimoni' => 'Saya bekerja sebagai operator mesin di pabrik Honda. Program ini memberikan saya kesempatan untuk belajar teknologi otomotif Jepang yang canggih. Gaji saya sekarang 3.1 juta per bulan dan saya sangat senang dengan lingkungan kerja yang aman dan terorganisir.',
                'foto' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Manufaktur',
                'tahun' => 2023,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 7,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Rina Wati',
                'pekerjaan' => 'Nurse Assistant',
                'lokasi' => 'Tokyo General Hospital',
                'testimoni' => 'Bekerja sebagai nurse assistant di rumah sakit Tokyo adalah pengalaman yang sangat berharga. Saya belajar banyak tentang sistem kesehatan Jepang yang sangat baik. Gaji yang saya terima cukup untuk hidup nyaman di Tokyo dan membantu keluarga di Indonesia.',
                'foto' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Healthcare',
                'tahun' => 2022,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 8,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Eko Wijaya',
                'pekerjaan' => 'Welder',
                'lokasi' => 'Shipyard, Kobe',
                'testimoni' => 'Saya bekerja sebagai welder di galangan kapal di Kobe. Program ini memberikan saya kesempatan untuk mengembangkan skill welding dengan standar internasional. Gaji saya 3.5 juta per bulan dan saya sangat puas dengan program pelatihan yang diberikan perusahaan.',
                'foto' => 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Shipbuilding',
                'tahun' => 2023,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 9,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Lina Kurniawan',
                'pekerjaan' => 'Convenience Store Staff',
                'lokasi' => '7-Eleven, Osaka',
                'testimoni' => 'Bekerja di convenience store di Osaka adalah pengalaman yang menyenangkan. Saya belajar banyak tentang customer service ala Jepang dan sistem kerja yang efisien. Gaji yang saya terima cukup untuk hidup mandiri di Jepang.',
                'foto' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Retail',
                'tahun' => 2022,
                'rating' => 4,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 10,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Bambang Setiawan',
                'pekerjaan' => 'Forklift Operator',
                'lokasi' => 'Warehouse, Yokohama',
                'testimoni' => 'Saya bekerja sebagai forklift operator di gudang di Yokohama. Program ini memberikan saya kesempatan untuk belajar sistem logistik Jepang yang sangat efisien. Gaji saya 2.8 juta per bulan dan saya sangat senang dengan benefit yang diberikan.',
                'foto' => 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Logistics',
                'tahun' => 2023,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 11,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Sari Dewi',
                'pekerjaan' => 'Housekeeping',
                'lokasi' => 'Ryokan, Hakone',
                'testimoni' => 'Bekerja di ryokan tradisional di Hakone adalah pengalaman yang unik. Saya belajar tentang budaya tradisional Jepang dan cara melayani tamu dengan baik. Gaji yang saya terima cukup dan saya sangat menikmati lingkungan kerja yang damai.',
                'foto' => 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Hospitality',
                'tahun' => 2022,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 12,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Joko Susilo',
                'pekerjaan' => 'Fishery Worker',
                'lokasi' => 'Fishing Port, Hokkaido',
                'testimoni' => 'Saya bekerja di industri perikanan di Hokkaido. Program ini memberikan saya kesempatan untuk belajar teknik penangkapan ikan modern Jepang. Gaji saya 2.6 juta per bulan dan saya sangat senang dengan lingkungan kerja yang sehat dan alami.',
                'foto' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Fishery',
                'tahun' => 2023,
                'rating' => 4,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 13,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Diana Putri',
                'pekerjaan' => 'Kitchen Staff',
                'lokasi' => 'Restaurant, Fukuoka',
                'testimoni' => 'Bekerja di dapur restoran di Fukuoka adalah pengalaman yang sangat berharga. Saya belajar cara memasak masakan Jepang autentik dan teknik memasak yang profesional. Gaji yang saya terima cukup dan saya sangat senang dengan tim kerja yang solid.',
                'foto' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Food Service',
                'tahun' => 2022,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 14,
                'status' => 'Publish',
            ],
            [
                'nama' => 'Agus Prasetyo',
                'pekerjaan' => 'Maintenance Technician',
                'lokasi' => 'Factory, Nagoya',
                'testimoni' => 'Saya bekerja sebagai maintenance technician di pabrik di Nagoya. Program ini memberikan saya kesempatan untuk belajar teknologi maintenance Jepang yang sangat canggih. Gaji saya 3.3 juta per bulan dan saya sangat puas dengan program pelatihan yang berkelanjutan.',
                'foto' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
                'program' => 'Tokutei Ginou - Manufaktur',
                'tahun' => 2023,
                'rating' => 5,
                'video_url' => null,
                'video_file' => null,
                'urutan' => 15,
                'status' => 'Publish',
            ],
        ];

        DB::table('kisah_sukses')->insert($kisahSukses);
    }
}
